# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  jupyterhub:
    build:
      context: ./jupyterhub
      args:
        JUPYTERHUB_VERSION: 0.9.3
    restart: always
    image: jupyterhub_hub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      #- "data:/home/capgemini/hubdata"
    ports:
      - "8000:8000"
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: jupyterhub-user
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
#      DOCKER_SPAWN_CMD: start-singleuser.sh
      HUB_IP: jupyterhub
    command: >
      jupyterhub   

networks:
  default:
    external:
      name: jupyterhub-network
